# Your workflow name.
name: Build Docker Image

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflow jobs.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository code.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to DockerHub (optional - only if you plan to push to DockerHub)
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build --no-cache -t my-app-image:latest .
